if __name__ == '__main__':
    from . import MegaModel
    import models
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-o', help='outfile', dest='out')
    parser.add_argument('-i', help='indent', dest='indent', type=int, default=2)
    args = parser.parse_args()

    # print('core');
    #
    # for name in dir(models.core):
    #     if name == 'ModuleModel':
    #         continue
    #     obj = getattr(models.core, name)
    #     if getattr(obj, 'schema_json', None):
    #         print('\t', name)
    #         try:
    #             obj.schema_json()
    #         except RecursionError as e:
    #             print('ERROR', name, e)

    print('MetricDefAttachToParams')
    models.aws_cloudwatch.MetricDefAttachToParams.schema_json()

    # print('_interface_methods')
    #
    # for name in dir(models._interface_methods):
    #     if name == 'ModuleModel':
    #         continue
    #     obj = getattr(models._interface_methods, name)
    #     if getattr(obj, 'schema_json', None):
    #         print('\t', name)
    #         try:
    #             obj.schema_json()
    #         except RecursionError as e:
    #             print('ERROR', name, e)
    #
    #
    #
    print('aws_apigateway')

    for name in dir(models.aws_apigateway):
        if name == 'ModuleModel':
            continue
        obj = getattr(models.aws_apigateway, name)
        if getattr(obj, 'schema_json', None):
            print('\t', name)
            try:
                obj.schema_json()
            except RecursionError as e:
                print('ERROR', name, e)

    # print('assertions'); models.assertions.ModuleModel.schema_json()
    # print('assets'); models.assets.ModuleModel.schema_json()
    # print('aws_accessanalyzer'); models.aws_accessanalyzer.ModuleModel.schema_json()
    # print('aws_acmpca'); models.aws_acmpca.ModuleModel.schema_json()
    # print('aws_amazonmq'); models.aws_amazonmq.ModuleModel.schema_json()
    # print('aws_amplify'); models.aws_amplify.ModuleModel.schema_json()
    # print('aws_amplifyuibuilder'); models.aws_amplifyuibuilder.ModuleModel.schema_json()
    # print('aws_apigateway'); models.aws_apigateway.ModuleModel.schema_json()
    # print('aws_apigatewayv2'); models.aws_apigatewayv2.ModuleModel.schema_json()
    # print('aws_appconfig'); models.aws_appconfig.ModuleModel.schema_json()
    # print('aws_appflow'); models.aws_appflow.ModuleModel.schema_json()
    # print('aws_appintegrations'); models.aws_appintegrations.ModuleModel.schema_json()
    # print('aws_applicationautoscaling'); models.aws_applicationautoscaling.ModuleModel.schema_json()
    # print('aws_applicationinsights'); models.aws_applicationinsights.ModuleModel.schema_json()
    # print('aws_appmesh'); models.aws_appmesh.ModuleModel.schema_json()
    # print('aws_apprunner'); models.aws_apprunner.ModuleModel.schema_json()
    # print('aws_appstream'); models.aws_appstream.ModuleModel.schema_json()
    # print('aws_appsync'); models.aws_appsync.ModuleModel.schema_json()
    # print('aws_aps'); models.aws_aps.ModuleModel.schema_json()
    # print('aws_athena'); models.aws_athena.ModuleModel.schema_json()
    # print('aws_auditmanager'); models.aws_auditmanager.ModuleModel.schema_json()
    # print('aws_autoscaling'); models.aws_autoscaling.ModuleModel.schema_json()
    # print('aws_autoscaling_common'); models.aws_autoscaling_common.ModuleModel.schema_json()
    # print('aws_autoscaling_hooktargets'); models.aws_autoscaling_hooktargets.ModuleModel.schema_json()
    # print('aws_autoscalingplans'); models.aws_autoscalingplans.ModuleModel.schema_json()
    # print('aws_backup'); models.aws_backup.ModuleModel.schema_json()
    # print('aws_backupgateway'); models.aws_backupgateway.ModuleModel.schema_json()
    # print('aws_batch'); models.aws_batch.ModuleModel.schema_json()
    # print('aws_billingconductor'); models.aws_billingconductor.ModuleModel.schema_json()
    # print('aws_budgets'); models.aws_budgets.ModuleModel.schema_json()
    # print('aws_cassandra'); models.aws_cassandra.ModuleModel.schema_json()
    # print('aws_ce'); models.aws_ce.ModuleModel.schema_json()
    # print('aws_certificatemanager'); models.aws_certificatemanager.ModuleModel.schema_json()
    # print('aws_chatbot'); models.aws_chatbot.ModuleModel.schema_json()
    # print('aws_cleanrooms'); models.aws_cleanrooms.ModuleModel.schema_json()
    # print('aws_cloud9'); models.aws_cloud9.ModuleModel.schema_json()
    # print('aws_cloudformation'); models.aws_cloudformation.ModuleModel.schema_json()
    # print('aws_cloudfront'); models.aws_cloudfront.ModuleModel.schema_json()
    # print('aws_cloudfront_origins'); models.aws_cloudfront_origins.ModuleModel.schema_json()
    # print('aws_cloudtrail'); models.aws_cloudtrail.ModuleModel.schema_json()
    # print('aws_cloudwatch'); models.aws_cloudwatch.ModuleModel.schema_json()
    # print('aws_cloudwatch_actions'); models.aws_cloudwatch_actions.ModuleModel.schema_json()
    # print('aws_codebuild'); models.aws_codebuild.ModuleModel.schema_json()
    # print('aws_codecommit'); models.aws_codecommit.ModuleModel.schema_json()
    # print('aws_codedeploy'); models.aws_codedeploy.ModuleModel.schema_json()
    # print('aws_codeguruprofiler'); models.aws_codeguruprofiler.ModuleModel.schema_json()
    # print('aws_codegurureviewer'); models.aws_codegurureviewer.ModuleModel.schema_json()
    # print('aws_codepipeline'); models.aws_codepipeline.ModuleModel.schema_json()
    # print('aws_codepipeline_actions'); models.aws_codepipeline_actions.ModuleModel.schema_json()
    # print('aws_codestar'); models.aws_codestar.ModuleModel.schema_json()
    # print('aws_codestarconnections'); models.aws_codestarconnections.ModuleModel.schema_json()
    # print('aws_codestarnotifications'); models.aws_codestarnotifications.ModuleModel.schema_json()
    # print('aws_cognito'); models.aws_cognito.ModuleModel.schema_json()
    # print('aws_comprehend'); models.aws_comprehend.ModuleModel.schema_json()
    # print('aws_config'); models.aws_config.ModuleModel.schema_json()
    # print('aws_connect'); models.aws_connect.ModuleModel.schema_json()
    # print('aws_connectcampaigns'); models.aws_connectcampaigns.ModuleModel.schema_json()
    # print('aws_controltower'); models.aws_controltower.ModuleModel.schema_json()
    # print('aws_cur'); models.aws_cur.ModuleModel.schema_json()
    # print('aws_customerprofiles'); models.aws_customerprofiles.ModuleModel.schema_json()
    # print('aws_databrew'); models.aws_databrew.ModuleModel.schema_json()
    # print('aws_datapipeline'); models.aws_datapipeline.ModuleModel.schema_json()
    # print('aws_datasync'); models.aws_datasync.ModuleModel.schema_json()
    # print('aws_dax'); models.aws_dax.ModuleModel.schema_json()
    # print('aws_detective'); models.aws_detective.ModuleModel.schema_json()
    # print('aws_devicefarm'); models.aws_devicefarm.ModuleModel.schema_json()
    # print('aws_devopsguru'); models.aws_devopsguru.ModuleModel.schema_json()
    # print('aws_directoryservice'); models.aws_directoryservice.ModuleModel.schema_json()
    # print('aws_dlm'); models.aws_dlm.ModuleModel.schema_json()
    # print('aws_dms'); models.aws_dms.ModuleModel.schema_json()
    # print('aws_docdb'); models.aws_docdb.ModuleModel.schema_json()
    # print('aws_docdbelastic'); models.aws_docdbelastic.ModuleModel.schema_json()
    # print('aws_dynamodb'); models.aws_dynamodb.ModuleModel.schema_json()
    # print('aws_ec2'); models.aws_ec2.ModuleModel.schema_json()
    # print('aws_ecr'); models.aws_ecr.ModuleModel.schema_json()
    # print('aws_ecr_assets'); models.aws_ecr_assets.ModuleModel.schema_json()
    # print('aws_ecs'); models.aws_ecs.ModuleModel.schema_json()
    # print('aws_ecs_patterns'); models.aws_ecs_patterns.ModuleModel.schema_json()
    # print('aws_efs'); models.aws_efs.ModuleModel.schema_json()
    # print('aws_eks'); models.aws_eks.ModuleModel.schema_json()
    # print('aws_elasticache'); models.aws_elasticache.ModuleModel.schema_json()
    # print('aws_elasticbeanstalk'); models.aws_elasticbeanstalk.ModuleModel.schema_json()
    # print('aws_elasticloadbalancing'); models.aws_elasticloadbalancing.ModuleModel.schema_json()
    # print('aws_elasticloadbalancingv2'); models.aws_elasticloadbalancingv2.ModuleModel.schema_json()
    # print('aws_elasticloadbalancingv2_actions'); models.aws_elasticloadbalancingv2_actions.ModuleModel.schema_json()
    # print('aws_elasticloadbalancingv2_targets'); models.aws_elasticloadbalancingv2_targets.ModuleModel.schema_json()
    # print('aws_elasticsearch'); models.aws_elasticsearch.ModuleModel.schema_json()
    # print('aws_emr'); models.aws_emr.ModuleModel.schema_json()
    # print('aws_emrcontainers'); models.aws_emrcontainers.ModuleModel.schema_json()
    # print('aws_emrserverless'); models.aws_emrserverless.ModuleModel.schema_json()
    # print('aws_entityresolution'); models.aws_entityresolution.ModuleModel.schema_json()
    # print('aws_events'); models.aws_events.ModuleModel.schema_json()
    # print('aws_events_targets'); models.aws_events_targets.ModuleModel.schema_json()
    # print('aws_eventschemas'); models.aws_eventschemas.ModuleModel.schema_json()
    # print('aws_evidently'); models.aws_evidently.ModuleModel.schema_json()
    # print('aws_finspace'); models.aws_finspace.ModuleModel.schema_json()
    # print('aws_fis'); models.aws_fis.ModuleModel.schema_json()
    # print('aws_fms'); models.aws_fms.ModuleModel.schema_json()
    # print('aws_forecast'); models.aws_forecast.ModuleModel.schema_json()
    # print('aws_frauddetector'); models.aws_frauddetector.ModuleModel.schema_json()
    # print('aws_fsx'); models.aws_fsx.ModuleModel.schema_json()
    # print('aws_gamelift'); models.aws_gamelift.ModuleModel.schema_json()
    # print('aws_globalaccelerator'); models.aws_globalaccelerator.ModuleModel.schema_json()
    # print('aws_globalaccelerator_endpoints'); models.aws_globalaccelerator_endpoints.ModuleModel.schema_json()
    # print('aws_glue'); models.aws_glue.ModuleModel.schema_json()
    # print('aws_grafana'); models.aws_grafana.ModuleModel.schema_json()
    # print('aws_greengrass'); models.aws_greengrass.ModuleModel.schema_json()
    # print('aws_greengrassv2'); models.aws_greengrassv2.ModuleModel.schema_json()
    # print('aws_groundstation'); models.aws_groundstation.ModuleModel.schema_json()
    # print('aws_guardduty'); models.aws_guardduty.ModuleModel.schema_json()
    # print('aws_healthimaging'); models.aws_healthimaging.ModuleModel.schema_json()
    # print('aws_healthlake'); models.aws_healthlake.ModuleModel.schema_json()
    # print('aws_iam'); models.aws_iam.ModuleModel.schema_json()
    # print('aws_identitystore'); models.aws_identitystore.ModuleModel.schema_json()
    # print('aws_imagebuilder'); models.aws_imagebuilder.ModuleModel.schema_json()
    # print('aws_inspector'); models.aws_inspector.ModuleModel.schema_json()
    # print('aws_inspectorv2'); models.aws_inspectorv2.ModuleModel.schema_json()
    # print('aws_internetmonitor'); models.aws_internetmonitor.ModuleModel.schema_json()
    # print('aws_iot'); models.aws_iot.ModuleModel.schema_json()
    # print('aws_iot1click'); models.aws_iot1click.ModuleModel.schema_json()
    # print('aws_iotanalytics'); models.aws_iotanalytics.ModuleModel.schema_json()
    # print('aws_iotcoredeviceadvisor'); models.aws_iotcoredeviceadvisor.ModuleModel.schema_json()
    # print('aws_iotevents'); models.aws_iotevents.ModuleModel.schema_json()
    # print('aws_iotfleethub'); models.aws_iotfleethub.ModuleModel.schema_json()
    # print('aws_iotfleetwise'); models.aws_iotfleetwise.ModuleModel.schema_json()
    # print('aws_iotsitewise'); models.aws_iotsitewise.ModuleModel.schema_json()
    # print('aws_iotthingsgraph'); models.aws_iotthingsgraph.ModuleModel.schema_json()
    # print('aws_iottwinmaker'); models.aws_iottwinmaker.ModuleModel.schema_json()
    # print('aws_iotwireless'); models.aws_iotwireless.ModuleModel.schema_json()
    # print('aws_ivs'); models.aws_ivs.ModuleModel.schema_json()
    # print('aws_ivschat'); models.aws_ivschat.ModuleModel.schema_json()
    # print('aws_kafkaconnect'); models.aws_kafkaconnect.ModuleModel.schema_json()
    # print('aws_kendra'); models.aws_kendra.ModuleModel.schema_json()
    # print('aws_kendraranking'); models.aws_kendraranking.ModuleModel.schema_json()
    # print('aws_kinesis'); models.aws_kinesis.ModuleModel.schema_json()
    # print('aws_kinesisanalytics'); models.aws_kinesisanalytics.ModuleModel.schema_json()
    # print('aws_kinesisanalyticsv2'); models.aws_kinesisanalyticsv2.ModuleModel.schema_json()
    # print('aws_kinesisfirehose'); models.aws_kinesisfirehose.ModuleModel.schema_json()
    # print('aws_kinesisvideo'); models.aws_kinesisvideo.ModuleModel.schema_json()
    # print('aws_kms'); models.aws_kms.ModuleModel.schema_json()
    # print('aws_lakeformation'); models.aws_lakeformation.ModuleModel.schema_json()
    # print('aws_lambda'); models.aws_lambda.ModuleModel.schema_json()
    # print('aws_lambda_destinations'); models.aws_lambda_destinations.ModuleModel.schema_json()
    # print('aws_lambda_event_sources'); models.aws_lambda_event_sources.ModuleModel.schema_json()
    # print('aws_lambda_nodejs'); models.aws_lambda_nodejs.ModuleModel.schema_json()
    # print('aws_lex'); models.aws_lex.ModuleModel.schema_json()
    # print('aws_licensemanager'); models.aws_licensemanager.ModuleModel.schema_json()
    # print('aws_lightsail'); models.aws_lightsail.ModuleModel.schema_json()
    # print('aws_location'); models.aws_location.ModuleModel.schema_json()
    # print('aws_logs'); models.aws_logs.ModuleModel.schema_json()
    # print('aws_logs_destinations'); models.aws_logs_destinations.ModuleModel.schema_json()
    # print('aws_lookoutequipment'); models.aws_lookoutequipment.ModuleModel.schema_json()
    # print('aws_lookoutmetrics'); models.aws_lookoutmetrics.ModuleModel.schema_json()
    # print('aws_lookoutvision'); models.aws_lookoutvision.ModuleModel.schema_json()
    # print('aws_m2'); models.aws_m2.ModuleModel.schema_json()
    # print('aws_macie'); models.aws_macie.ModuleModel.schema_json()
    # print('aws_managedblockchain'); models.aws_managedblockchain.ModuleModel.schema_json()
    # print('aws_mediaconnect'); models.aws_mediaconnect.ModuleModel.schema_json()
    # print('aws_mediaconvert'); models.aws_mediaconvert.ModuleModel.schema_json()
    # print('aws_medialive'); models.aws_medialive.ModuleModel.schema_json()
    # print('aws_mediapackage'); models.aws_mediapackage.ModuleModel.schema_json()
    # print('aws_mediapackagev2'); models.aws_mediapackagev2.ModuleModel.schema_json()
    # print('aws_mediastore'); models.aws_mediastore.ModuleModel.schema_json()
    # print('aws_mediatailor'); models.aws_mediatailor.ModuleModel.schema_json()
    # print('aws_memorydb'); models.aws_memorydb.ModuleModel.schema_json()
    # print('aws_msk'); models.aws_msk.ModuleModel.schema_json()
    # print('aws_mwaa'); models.aws_mwaa.ModuleModel.schema_json()
    # print('aws_neptune'); models.aws_neptune.ModuleModel.schema_json()
    # print('aws_networkfirewall'); models.aws_networkfirewall.ModuleModel.schema_json()
    # print('aws_networkmanager'); models.aws_networkmanager.ModuleModel.schema_json()
    # print('aws_nimblestudio'); models.aws_nimblestudio.ModuleModel.schema_json()
    # print('aws_oam'); models.aws_oam.ModuleModel.schema_json()
    # print('aws_omics'); models.aws_omics.ModuleModel.schema_json()
    # print('aws_opensearchserverless'); models.aws_opensearchserverless.ModuleModel.schema_json()
    # print('aws_opensearchservice'); models.aws_opensearchservice.ModuleModel.schema_json()
    # print('aws_opsworks'); models.aws_opsworks.ModuleModel.schema_json()
    # print('aws_opsworkscm'); models.aws_opsworkscm.ModuleModel.schema_json()
    # print('aws_organizations'); models.aws_organizations.ModuleModel.schema_json()
    # print('aws_osis'); models.aws_osis.ModuleModel.schema_json()
    # print('aws_panorama'); models.aws_panorama.ModuleModel.schema_json()
    # print('aws_pcaconnectorad'); models.aws_pcaconnectorad.ModuleModel.schema_json()
    # print('aws_personalize'); models.aws_personalize.ModuleModel.schema_json()
    # print('aws_pinpoint'); models.aws_pinpoint.ModuleModel.schema_json()
    # print('aws_pinpointemail'); models.aws_pinpointemail.ModuleModel.schema_json()
    # print('aws_pipes'); models.aws_pipes.ModuleModel.schema_json()
    # print('aws_proton'); models.aws_proton.ModuleModel.schema_json()
    # print('aws_qldb'); models.aws_qldb.ModuleModel.schema_json()
    # print('aws_quicksight'); models.aws_quicksight.ModuleModel.schema_json()
    # print('aws_ram'); models.aws_ram.ModuleModel.schema_json()
    # print('aws_rds'); models.aws_rds.ModuleModel.schema_json()
    # print('aws_redshift'); models.aws_redshift.ModuleModel.schema_json()
    # print('aws_redshiftserverless'); models.aws_redshiftserverless.ModuleModel.schema_json()
    # print('aws_refactorspaces'); models.aws_refactorspaces.ModuleModel.schema_json()
    # print('aws_rekognition'); models.aws_rekognition.ModuleModel.schema_json()
    # print('aws_resiliencehub'); models.aws_resiliencehub.ModuleModel.schema_json()
    # print('aws_resourceexplorer2'); models.aws_resourceexplorer2.ModuleModel.schema_json()
    # print('aws_resourcegroups'); models.aws_resourcegroups.ModuleModel.schema_json()
    # print('aws_robomaker'); models.aws_robomaker.ModuleModel.schema_json()
    # print('aws_rolesanywhere'); models.aws_rolesanywhere.ModuleModel.schema_json()
    # print('aws_route53'); models.aws_route53.ModuleModel.schema_json()
    # print('aws_route53_patterns'); models.aws_route53_patterns.ModuleModel.schema_json()
    # print('aws_route53_targets'); models.aws_route53_targets.ModuleModel.schema_json()
    # print('aws_route53recoverycontrol'); models.aws_route53recoverycontrol.ModuleModel.schema_json()
    # print('aws_route53recoveryreadiness'); models.aws_route53recoveryreadiness.ModuleModel.schema_json()
    # print('aws_route53resolver'); models.aws_route53resolver.ModuleModel.schema_json()
    # print('aws_rum'); models.aws_rum.ModuleModel.schema_json()
    # print('aws_s3'); models.aws_s3.ModuleModel.schema_json()
    # print('aws_s3_assets'); models.aws_s3_assets.ModuleModel.schema_json()
    # print('aws_s3_deployment'); models.aws_s3_deployment.ModuleModel.schema_json()
    # print('aws_s3_notifications'); models.aws_s3_notifications.ModuleModel.schema_json()
    # print('aws_s3objectlambda'); models.aws_s3objectlambda.ModuleModel.schema_json()
    # print('aws_s3outposts'); models.aws_s3outposts.ModuleModel.schema_json()
    # print('aws_sagemaker'); models.aws_sagemaker.ModuleModel.schema_json()
    # print('aws_sam'); models.aws_sam.ModuleModel.schema_json()
    # print('aws_scheduler'); models.aws_scheduler.ModuleModel.schema_json()
    # print('aws_sdb'); models.aws_sdb.ModuleModel.schema_json()
    # print('aws_secretsmanager'); models.aws_secretsmanager.ModuleModel.schema_json()
    # print('aws_securityhub'); models.aws_securityhub.ModuleModel.schema_json()
    # print('aws_servicecatalog'); models.aws_servicecatalog.ModuleModel.schema_json()
    # print('aws_servicecatalogappregistry'); models.aws_servicecatalogappregistry.ModuleModel.schema_json()
    # print('aws_servicediscovery'); models.aws_servicediscovery.ModuleModel.schema_json()
    # print('aws_ses'); models.aws_ses.ModuleModel.schema_json()
    # print('aws_ses_actions'); models.aws_ses_actions.ModuleModel.schema_json()
    # print('aws_shield'); models.aws_shield.ModuleModel.schema_json()
    # print('aws_signer'); models.aws_signer.ModuleModel.schema_json()
    # print('aws_simspaceweaver'); models.aws_simspaceweaver.ModuleModel.schema_json()
    # print('aws_sns'); models.aws_sns.ModuleModel.schema_json()
    # print('aws_sns_subscriptions'); models.aws_sns_subscriptions.ModuleModel.schema_json()
    # print('aws_sqs'); models.aws_sqs.ModuleModel.schema_json()
    # print('aws_ssm'); models.aws_ssm.ModuleModel.schema_json()
    # print('aws_ssmcontacts'); models.aws_ssmcontacts.ModuleModel.schema_json()
    # print('aws_ssmincidents'); models.aws_ssmincidents.ModuleModel.schema_json()
    # print('aws_sso'); models.aws_sso.ModuleModel.schema_json()
    # print('aws_stepfunctions'); models.aws_stepfunctions.ModuleModel.schema_json()
    # print('aws_stepfunctions_tasks'); models.aws_stepfunctions_tasks.ModuleModel.schema_json()
    # print('aws_supportapp'); models.aws_supportapp.ModuleModel.schema_json()
    # print('aws_synthetics'); models.aws_synthetics.ModuleModel.schema_json()
    # print('aws_systemsmanagersap'); models.aws_systemsmanagersap.ModuleModel.schema_json()
    # print('aws_timestream'); models.aws_timestream.ModuleModel.schema_json()
    # print('aws_transfer'); models.aws_transfer.ModuleModel.schema_json()
    # print('aws_verifiedpermissions'); models.aws_verifiedpermissions.ModuleModel.schema_json()
    # print('aws_voiceid'); models.aws_voiceid.ModuleModel.schema_json()
    # print('aws_vpclattice'); models.aws_vpclattice.ModuleModel.schema_json()
    # print('aws_waf'); models.aws_waf.ModuleModel.schema_json()
    # print('aws_wafregional'); models.aws_wafregional.ModuleModel.schema_json()
    # print('aws_wafv2'); models.aws_wafv2.ModuleModel.schema_json()
    # print('aws_wisdom'); models.aws_wisdom.ModuleModel.schema_json()
    # print('aws_workspaces'); models.aws_workspaces.ModuleModel.schema_json()
    # print('aws_workspacesweb'); models.aws_workspacesweb.ModuleModel.schema_json()
    # print('aws_xray'); models.aws_xray.ModuleModel.schema_json()
    # print('cloud_assembly_schema'); models.cloud_assembly_schema.ModuleModel.schema_json()
    # print('cloudformation_include'); models.cloudformation_include.ModuleModel.schema_json()
    # print('custom_resources'); models.custom_resources.ModuleModel.schema_json()
    # print('cx_api'); models.cx_api.ModuleModel.schema_json()
    # print('lambda_layer_awscli'); models.lambda_layer_awscli.ModuleModel.schema_json()
    # print('lambda_layer_kubectl'); models.lambda_layer_kubectl.ModuleModel.schema_json()
    # print('lambda_layer_node_proxy_agent'); models.lambda_layer_node_proxy_agent.ModuleModel.schema_json()
    # print('pipelines'); models.pipelines.ModuleModel.schema_json()
    # print('region_info'); models.region_info.ModuleModel.schema_json()
    # print('triggers'); models.triggers.ModuleModel.schema_json()
    # print('constructs'); models.constructs.ModuleModel.schema_json()
    #
    # MegaModel.update_forward_refs()
    # schema = MegaModel.schema_json(indent=args.indent)
    # if args.outfile:
    #     with open(args.outfile, 'w') as f:
    #         f.write(schema)
    # else:
    #     print(schema)
